{1501}{}{Claro, benzinho. Vou ficar aqui.}
{1502}{}{Tá bem, benzinho, só toma cuidado lá fora!}
{1503}{}{Certo, vou esperar aqui por você, querida.}
{1504}{}{Sem problema, docinho. Vou ficar aqui.}
{1505}{}{Eu espero, mas volta logo, meu amor!}
{1510}{}{Você voltou! Eu senti sua falta, benzinho!}
{1511}{}{Ei, meu amor, ainda bem que você voltou pra mim.}
{1512}{}{Aí está você! Eu já estava começando a me preocupar, querida.}
{1513}{}{Ei, querida! Vamos nessa!}
{1514}{}{Meu benzinho voltou! Vamos, docinho.}
{1520}{}{Eu iria com você, mas parece que você já tem gente demais com você, benzinho.}
