language: minimal
dist: bionic
sudo: false

cache:
  directories:
    - $HOME/.cache/build

before_install:
  - ./extra/prepare.sh

script:
  - ./extra/buildall.sh
  - ./extra/publish.sh

env:
  global:
    - sfall_version: 4.1.9.1
    - mpack_version: 4.1.9.1
    - mod_name: rpu
    - extra_dir: extra
    - bin_dir: extra/bin
    - appearance_dir: appearance
    - release_dir: release
    - mods_dir: release/mods
    - mpack_7z: mpack.7z
    - wine: "WINEARCH=win32 WINEDEBUG=-all wine"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: rpu*.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master
  draft: true
