language: java
dist: bionic
sudo: false

cache:
  directories:
    - $HOME/.cache/build

services:
  - xvfb

addons:
  apt:
    update: true
    packages:
      - crudini
      - dos2unix
      - gcc
      - moreutils
      - p7zip
      - wine-stable
      - wine32

before_install:
  - ./extra/prepare.sh
  - wineboot

after_success:
  - wineserver -k

script:
  - ./extra/buildall.sh
  - ./extra/publish.sh

env:
  global:
    - sfall_version: 4.2.4
    - mpack_version: 4.2.4
    - mod_name: rpu
    - extra_dir: extra
    - bin_dir: extra/bin
    - appearance_dir: appearance
    - appearance_repo: BGforgeNet/Fallout2_Hero_Appearance
    - party_orders_repo: BGforgeNet/Fallout2_Party_Orders
    - hq_music_repo: BGforgeNet/Fallout2-HQ-music
    - npc_armor_repo: BGforgeNet/Fallout2_NPC_Armor
    - release_dir: release
    - trans_dir: translations
    - mods_dir: release/mods
    - mpack_7z: mpack.7z
    - WINEARCH: win32
    - WINEDEBUG: -all

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - rpu*.zip
    - rpu*.dat
    - rpu*.exe
  skip_cleanup: true
  on:
    tags: true
    branch: master
