{1501}{}{Jasně, brouku. Počkám tady.}
{1502}{}{Dobře, bejby, jen dávej na sebe pozor venku!}
{1503}{}{Dobře, počkám tu na tebe, brouku.}
{1504}{}{Žádný problém, cukroušku. Zůstanu tady.}
{1505}{}{Počkám, ale pospěš si zpátky, lásko!}
{1510}{}{Jsi zpátky! Stýskalo se mi, brouku!}
{1511}{}{Hej, lásko, jsem ráda, že jsi zpátky.}
{1512}{}{No konečně! Už jsem si začínala dělat starosti, brouku.}
{1513}{}{Hej, brouku! Jdeme!}
{1514}{}{Můj brouček je zpátky! Jdeme, cukroušku.}
{1520}{}{Šla bych s tebou, ale vypadá to, že už máš moc lidí s sebou, brouku.}
