{1501}{}{D'accord, mon chou. Je reste ici.}
{1502}{}{OK, mon chou, fais juste attention dehors !}
{1503}{}{Très bien, je t'attends ici, mon coeur.}
{1504}{}{Pas de problème, mon amour. Je reste là.}
{1505}{}{J'attends, mais reviens vite, mon ange !}
{1510}{}{Te revoilà ! Tu m'as manqué, mon chou !}
{1511}{}{Hé, mon amour, je suis contente de te revoir.}
{1512}{}{Ah, te voilà ! Je commençais à m'inquiéter, mon chou.}
{1513}{}{Hé, mon coeur ! On y va !}
{1514}{}{Mon chou est de retour ! Allez, mon amour.}
{1520}{}{Je viendrais bien avec toi, mais on dirait que tu as déjà trop de monde avec toi, mon chou.}
