{1501}{}{Được thôi, anh yêu. Em sẽ đợi ở đây.}
{1502}{}{Được rồi, anh yêu, nhớ cẩn thận ngoài kia nhé!}
{1503}{}{Được thôi, em sẽ đợi anh ngay tại đây, anh yêu.}
{1504}{}{Không sao đâu, anh yêu. Em sẽ ở yên đây.}
{1505}{}{Em sẽ đợi, nhưng nhớ quay lại nhanh nhé, anh yêu!}
{1510}{}{Anh về rồi! Em nhớ anh lắm, anh yêu!}
{1511}{}{Này anh yêu, mừng vì anh quay lại đón em.}
{1512}{}{Cuối cùng anh cũng về! Em bắt đầu lo rồi, anh yêu.}
{1513}{}{Này anh yêu! Đi thôi!}
{1514}{}{Anh yêu của em về rồi! Đi nào, anh yêu.}
{1520}{}{Em sẽ đi cùng anh, nhưng hình như anh đã có quá nhiều người đi theo rồi, anh yêu.}
