{1501}{}{Persze, bébi. Itt várlak.}
{1502}{}{Rendben, bébi, csak légy óvatos odakint!}
{1503}{}{Jó, itt várok rád, drágám.}
{1504}{}{Semmi gond, édesem. Itt maradok.}
{1505}{}{Várok, de siess vissza, kedvesem!}
{1510}{}{Visszajöttél! Hiányoztál, bébi!}
{1511}{}{Szia, kedvesem, örülök, hogy visszajöttél értem.}
{1512}{}{Végre itt vagy! Már kezdtem aggódni, cicabogár.}
{1513}{}{Szia, drágám! Induljunk!}
{1514}{}{Visszajött a bébim! Gyerünk, édesem.}
{1520}{}{Mennék veled, de úgy tűnik, már túl sokan vannak veled, bébi.}
