{1501}{}{Jasne, kochanie. Będę tu czekać.}
{1502}{}{Dobra, kochanie, tylko uważaj tam na siebie!}
{1503}{}{Dobrze, poczekam tu na ciebie, skarbie.}
{1504}{}{Nie ma sprawy, słonko. Zostanę tutaj.}
{1505}{}{Poczekam, ale wracaj szybko, kochanie!}
{1510}{}{Wróciłeś! Tęskniłam, kochanie!}
{1511}{}{Hej, skarbie, dobrze że jesteś z powrotem.}
{1512}{}{No nareszcie! Zaczynałam się martwić, misiu.}
{1513}{}{Hej, kochanie! Ruszajmy!}
{1514}{}{Moje kochanie wróciło! Chodźmy, słonko.}
{1520}{}{Poszłabym z tobą, ale wygląda na to, że masz już za dużo ludzi z sobą, kochanie.}
