{1501}{}{D'accord, ma chérie. Je reste ici.}
{1502}{}{OK, ma chérie, fais juste attention dehors !}
{1503}{}{Très bien, je t'attends ici, ma belle.}
{1504}{}{Pas de problème, ma puce. Je reste là.}
{1505}{}{J'attends, mais reviens vite, mon amour !}
{1510}{}{Te revoilà ! Tu m'as manquée, ma chérie !}
{1511}{}{Hé, mon amour, contente que tu sois revenue me chercher.}
{1512}{}{Ah, te voilà ! Je commençais à m'inquiéter, ma chérie.}
{1513}{}{Hé, ma belle ! On y va !}
{1514}{}{Ma chérie est de retour ! Allez, mon amour.}
{1520}{}{Je viendrais bien avec toi, mais on dirait que tu as déjà trop de monde avec toi, ma chérie.}
