{1501}{}{Va bene, baby. Resto qui.}
{1502}{}{Ok, baby, ma fai attenzione là fuori!}
{1503}{}{D'accordo, ti aspetto qui, tesoro.}
{1504}{}{Nessun problema, amore. Rimango qui.}
{1505}{}{Aspetto, ma torna presto, amore!}
{1510}{}{Sei tornato! Mi sei mancato, baby!}
{1511}{}{Ehi, amore, sono felice di rivederti.}
{1512}{}{Eccoti! Cominciavo a preoccuparmi, cucciolo.}
{1513}{}{Ehi, tesoro! Andiamo!}
{1514}{}{Il mio baby è tornato! Forza, zuccherino.}
{1520}{}{Verrei con te, ma mi sa che hai già troppa gente con te, baby.}
