{1501}{}{Claro, cariño. Me quedaré aquí.}
{1502}{}{Vale, cariño, sólo ten cuidado ahí fuera.}
{1503}{}{De acuerdo, te esperaré aquí, querido.}
{1504}{}{No hay problema, azúcar. Me quedaré aquí.}
{1505}{}{Esperaré, pero vuelve pronto, amor.}
{1510}{}{¡Has vuelto! Te he echado de menos, cariño.}
{1511}{}{Eh, amor, me alegro de que hayas vuelto por mí.}
{1512}{}{¡Ahí estás! Ya empezaba a preocuparme, tesoro.}
{1513}{}{¡Eh, querido! ¡Vámonos!}
{1514}{}{¡Mi cariño ha vuelto! Vamos, azúcar.}
{1520}{}{Iría contigo, pero parece que ya llevas demasiada gente contigo, cariño.}
