{1501}{}{Visst, älskling. Jag väntar här.}
{1502}{}{Okej, älskling, var bara försiktig där ute!}
{1503}{}{Okej, jag väntar här på dig, hjärtat.}
{1504}{}{Inga problem, sötnos. Jag stannar här.}
{1505}{}{Jag väntar, men skynda dig tillbaka, älskling!}
{1510}{}{Du är tillbaka! Jag saknade dig, älskling!}
{1511}{}{Hej älskling, vad skönt att du kom tillbaka för mig.}
{1512}{}{Där är du ju! Jag började bli orolig, sötnos.}
{1513}{}{Hej hjärtat! Nu går vi!}
{1514}{}{Min älskling är tillbaka! Kom igen, sötnos.}
{1520}{}{Jag skulle följa med, men det ser ut som att du redan har för många med dig, älskling.}
