{1501}{}{Được thôi, chị yêu. Em sẽ đợi ở đây.}
{1502}{}{Được rồi, chị yêu, nhớ cẩn thận ngoài kia nhé!}
{1503}{}{Được thôi, em sẽ đợi chị ngay tại đây, chị yêu.}
{1504}{}{Không sao đâu, chị yêu. Em sẽ ở yên đây.}
{1505}{}{Em sẽ đợi, nhưng nhớ quay lại nhanh nhé, chị yêu!}
{1510}{}{Chị về rồi! Em nhớ chị lắm, chị yêu!}
{1511}{}{Này chị yêu, mừng vì chị quay lại đón em.}
{1512}{}{Cuối cùng chị cũng về! Em bắt đầu lo rồi, chị yêu.}
{1513}{}{Này chị yêu! Đi thôi!}
{1514}{}{Chị yêu của em về rồi! Đi nào, chị yêu.}
{1520}{}{Em sẽ đi cùng chị, nhưng hình như chị đã có quá nhiều người đi theo rồi, chị yêu.}
