{1501}{}{Klar, Baby. Ich warte hier.}
{1502}{}{OK, Baby, aber pass da draußen auf!}
{1503}{}{Alles klar, ich warte hier auf dich, Schnuckelchen.}
{1504}{}{Kein Problem, Zuckerschnute. Ich bleib hier.}
{1505}{}{Ich warte, aber komm schnell zurück, Liebling!}
{1510}{}{Du bist zurück! Ich hab dich vermisst, Baby!}
{1511}{}{Hey, Liebling, schön dass du wieder da bist.}
{1512}{}{Da bist du ja! Ich hab mir schon Sorgen gemacht, Schnuckelchen.}
{1513}{}{Hey, Spatzl! Los geht's!}
{1514}{}{Mein Baby ist wieder da! Los, Schnuckelchen.}
{1520}{}{Ich würd ja mitkommen, aber du hast wohl schon zu viele Leute dabei, Baby.}
